debug:
  hitbox: false
  exception: false
module:
  model: true
  player-animation: true
metrics: true
sight-trace: true
item: leather_horse_armor
max-sight: -1
min-sight: 5
lock-on-play-animation: true
namespace: "bettermodel"
pack-type: zip #folder, zip
build-folder-location: BetterModel/build
disable-generating-legacy-models: false
follow-mob-invisibility: true
animated-texture-frame-time: 10
create-pack-mcmeta: true
use-purpur-afk: true
version-check: true