metrics: true
sight-trace: true
item: leather_horse_armor
max-sight: 45
min-sight: 5
lock-on-play-animation: true
keyframe-threshold: 2
enable-player-limb: true
namespace: "bettermodel"
pack-type: folder #folder, zip
build-folder-location: BetterModel/build
